"""add nrFirma to servicii

Revision ID: 91bab3cfb574
Revises: dd43d3fc8596
Create Date: 2026-03-17 16:41:25.656422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bab3cfb574'
down_revision = 'dd43d3fc8596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicii', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nrFirma', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicii', schema=None) as batch_op:
        batch_op.drop_column('nrFirma')

    # ### end Alembic commands ###
