"""add gdpr fields

Revision ID: dd43d3fc8596
Revises: 
Create Date: 2026-03-17 12:05:50.012168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd43d3fc8596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gdprAcceptat', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('newsletterAcceptat', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('termeniAcceptati', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_column('termeniAcceptati')
        batch_op.drop_column('newsletterAcceptat')
        batch_op.drop_column('gdprAcceptat')

    # ### end Alembic commands ###
